<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1701;1702;CS0162;CS0414;CS1591;CS8981;IDE1006;SYSLIB0021</NoWarn>
    <PackageId>Lemutec.RemoteViewing</PackageId>
    <Product>Lemutec.RemoteViewing</Product>
    <AssemblyName>Lemutec.RemoteViewing</AssemblyName>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <AssemblyVersion>1.2.1.0</AssemblyVersion>
    <FileVersion>1.2.1.0</FileVersion>
    <Version>$(VersionPrefix)1.2.1.0</Version>
    <Authors>James F. Bellinger, Lemutec</Authors>
    <Company>James F. Bellinger, Lemutec</Company>
    <Description>RemoteViewing is a .NET-native VNC client and server library. It supports Raw, Hextile, Copyrect, and Zlib encodings, and includes a Windows Forms and WPF control to make embedding VNC in your program extremely easy.</Description>
    <PackageProjectUrl>https://github.com/lemutec/RemoteViewing</PackageProjectUrl>
    <RepositoryUrl>https://github.com/lemutec/RemoteViewing</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>csharp vnc-client vnc-server vnc rfb</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>logo.png</PackageIcon>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="" />
    <None Include="..\logo.png" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>