<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net9.0-windows</TargetFrameworks>
    <LangVersion>preview</LangVersion>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>1701;1702;CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RemoteViewing\RemoteViewing.csproj" />
    <ProjectReference Include="..\RemoteViewing.WPF\RemoteViewing.WPF.csproj" />
  </ItemGroup>
</Project>